apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: todo-app
          image: prgacr123test.azurecr.io/todo-app
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 8080
              name: todo-app